# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rLm-tKFkZHhg7XmHuY_7vYv4KxZFL5pC
"""

import streamlit as st
import pandas as pd
import joblib

model = joblib.load('salary_predictor.pkl')

st.title("💼 Job Salary Prediction")

term = st.selectbox("Term", ['Full-time', 'Part-time', 'Contract', 'Internship'])
experience = st.slider("Years of Experience", 0, 30, 1)
qualification = st.selectbox("Qualification", ['Bachelor', 'Master', 'Diploma', 'High School', 'PhD'])
sex = st.selectbox("Sex", ['Male', 'Female', 'Other'])
language = st.text_input("Language", "English")
age = st.slider("Age", 18, 65, 25)
location = st.selectbox("Location", ['Phnom Penh', 'Siem Reap', 'Battambang'])
level = st.selectbox("Job Level", ['Entry', 'Mid', 'Senior', 'Manager'])
job_title = st.text_input("Standardized Job Title", "Data Analyst")
category = st.text_input("Standardized Category", "IT")
industry = st.text_input("Standardized Industry", "Banking")

if st.button("Predict Salary"):
    input_data = pd.DataFrame([{
        'Term': term,
        'Year of Exp.': experience,
        'Qualification': qualification,
        'Sex': sex,
        'Language': language,
        'Age': age,
        'Location': location,
        'Level_Updated': level,
        'Standardized_Job_Title': job_title,
        'Standardized_Category': category,
        'Standardized_Industry': industry
    }])

    prediction = model.predict(input_data)[0]
    st.success(f"💰 Estimated Salary: ${prediction:,.2f}")
